from enum import Enum


class Keyword(Enum):
    STATUS = "STUDY STATUS"
    PROGRAM = "STUDY STATUS"
    INSTITUTE = "NIH INSTITUTE OR CENTER"
    METHOD = "DATA COLLECTION METHOD"
    DESIGN = "STUDY DESIGN"
    COHORTSIZE = "ESTIMATED COHORT SIZE"
    DATATYPES = "DATA TYPES"
    DOMAIN = "STUDY DOMAIN"
    PHS = "STUDY PHS"
    FOCUSPOPULATION = "STUDY POPULATION FOCUS"
